"""Init

Revision ID: ac5bdf66cfae
Revises:
Create Date: 2026-05-17 23:35:35.541520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "ac5bdf66cfae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_records",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("city_name", sa.String(length=255), nullable=False),
        sa.Column("queried_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index(op.f("ix_query_records_id"), "query_records", ["id"], unique=False)
    op.create_index(op.f("ix_query_records_city_name"), "query_records", ["city_name"], unique=False)
    op.create_index(op.f("ix_query_records_queried_at"), "query_records", ["queried_at"], unique=False)

    op.create_table(
        "weather_details",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("query_record_id", sa.Integer(), sa.ForeignKey("query_records.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("feels_like", sa.Float(), nullable=True),
        sa.Column("humidity", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("served_from_cache", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.create_index(op.f("ix_weather_details_query_record_id"), "weather_details", ["query_record_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_details_query_record_id"), table_name="weather_details")
    op.drop_table("weather_details")
    op.drop_index(op.f("ix_query_records_queried_at"), table_name="query_records")
    op.drop_index(op.f("ix_query_records_city_name"), table_name="query_records")
    op.drop_index(op.f("ix_query_records_id"), table_name="query_records")
    op.drop_table("query_records")
    # ### end Alembic commands ###